install angle-grinder
install ant
install asciiquarium
install automake
install bash
install bat
install cmake
install cmatrix
install coreutils
install cowsay
install cscope
install csv-fix
install diff-so-fancy
install direnv
install elasticsearch
install entr
install exa
install exercism
install fasd
install fd
install feedgnuplot
install figlet
install fx
install fzf
install gawk
install gifsicle
install git
install git-lfs
install gnu-sed
install gnupg
install gnupg@1.4
install go
install graphicsmagick
install graphviz
install gron
install highlight
install htop
install hub
install hyperfine
install jid
install jo
install jq
install json-c
install legit
install libstfl
install lolcat
install mhash
install mkcert
install mockserver
install moreutils
install neovim
install no-more-secrets
install noti
install osquery
install packer
install pidof
install prettyping
install pup
install pv
install pyenv
install rhash
install ripgrep
install rlwrap
install rpm
install rsstail
install shellcheck
install sl
install sloc
install socat
install spark
install sphinx-doc
install sqlite-analyzer
install ssh-copy-id
install tcping
install tcptraceroute
install termtosvg
install the_silver_searcher
install tig
install tinyproxy
install tj
install tldr
install tmux
install toilet
install tree
install valgrind
install vim
install visionmedia-watch
install vitetris
install wget
install wrk
install yarn
install zsh
install zsh-completions
